[theme]
primaryColor="#4285B4"
backgroundColor="#FFFAFA"
secondaryBackgroundColor="#4285B4"
textColor="#2E2E2E"
fontFamily="Helvetica"
font="sans serif"
borderColor = "#000000"
sidebarBorder=true
borderRadius = "8px"

[theme.sidebar]
textColor="#2E2E2E"
secondaryBackgroundColor="#4285B4"
backgroundColor="#F8F8FF"
borderColor="#4285B4"
fontFamily="Helvetica"
font="sans serif"